// Generated by CoffeeScript 1.6.3
/*
Copyright 2013 Simon Lydell

This file is part of yaba.

yaba is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser
General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

yaba is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with yaba. If not,
see <http://www.gnu.org/licenses/>.
*/

var readFileSync;

if (typeof XMLHttpRequest === "function") {
  readFileSync = function(path) {
    var request;
    request = new XMLHttpRequest;
    request.open("GET", path, false);
    request.send(null);
    if (request.status < 400) {
      return request.responseText;
    } else {
      throw new Error("Could not fetch " + path + ":\n" + request.responseText);
    }
  };
} else {
  readFileSync = require("fs").readFileSync;
}

module.exports = readFileSync;
